### ISSUE TITLE
What is the command / How can I train the model

### ISSUE THREAD

**Issue by jackywongboy** [zhaoxlpku/HKU-DASC7606-A2#2]
The script provide seem is for evaluation but not training?

And seem the evaluation script is not working too?
`
File "C:\Users\USER\miniconda3\envs\nlp_env\lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/path_of_llm/resolve/main/vocab.json
`

`
eval_fewshot.py", line 167, in get_model

    tokenizer = CodeGenTokenizer.from_pretrained(base_model)
  File "C:\Users\USER\miniconda3\envs\nlp_env\lib\site-packages\transformers\tokenization_utils_base.py", line 1800, in from_pretrained
    resolved_vocab_files[file_id] = cached_file(
  File "C:\Users\USER\miniconda3\envs\nlp_env\lib\site-packages\transformers\utils\hub.py", line 433, in cached_file
    raise EnvironmentError(
OSError: path_of_llm is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.
`

**Comment by zhaoxlpku** [comment]
For this assignment, training is not required. Please replace "path_of_llms" with the actual path where you have saved Phi-1.5.
